import { AuthContextProvider } from "@/AuthContext";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import MainContainer from "@/components/MainContainer";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Cerulean",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthContextProvider>
        <MainContainer>
          <Header />
          {children}
          <Footer />
        </MainContainer>
      </AuthContextProvider>
    </html>
  );
}
